name: meu_app
description: Meu primeiro app Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Pacotes que vocÃª pediu
  google_fonts: ^6.3.2
  http: ^1.6.0
  path_provider: ^2.1.5
  crypto: ^3.0.7
  ffi: ^2.1.4
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
    

flutter:
  uses-material-design: true

  assets:
    - lib/images/paisagem1.jpeg
    - lib/images/paisagem2.jpeg
    - lib/images/paisagem3.jpeg
    - lib/images/user1.jpeg
    - lib/images/user2.jpeg
    - lib/images/user3.png
    - lib/images/logo.png
